Document: asha
Title: Debian asha Manual
Author: <insert document author here>
Abstract: This manual describes what asha is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/asha/asha.sgml.gz

Format: postscript
Files: /usr/share/doc/asha/asha.ps.gz

Format: text
Files: /usr/share/doc/asha/asha.text.gz

Format: HTML
Index: /usr/share/doc/asha/html/index.html
Files: /usr/share/doc/asha/html/*.html
